### ISSUE TITLE
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find minitest-5.10.2 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by rogeriopradoj** [Starefossen/docker-github-pages#11]
```
➜ docker run -v "$PWD":/usr/src/app -p "4000:4000" starefossen/github-pages
Unable to find image 'starefossen/github-pages:latest' locally
latest: Pulling from starefossen/github-pages
90f4dba627d6: Pull complete
98c1a7514ba6: Pull complete
e970acb20b34: Pull complete
37b763b54c24: Pull complete
fda57ec1751e: Pull complete
7f76182f2170: Pull complete
179b7133d658: Pull complete
58a6fe250e07: Pull complete
Digest: sha256:e26cb38ed5dbc2b5c12b696a00266c052f51d315dd792e714761520640e62511
Status: Downloaded newer image for starefossen/github-pages:latest
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find minitest-5.10.2 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `map!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `materialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:159:in `specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:218:in `specs_for'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:207:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:21:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:101:in `setup'
	from /usr/local/bundle/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:23:in `load'
	from /usr/local/bundle/bin/jekyll:23:in `<main>'

```

Got the same error all times I try to run.

In order to provide more information, I'm trying to run against https://github.com/rogeriopradoj/phptestfest.org/tree/master/docs.

Thanks in advance.

**Comment by siliconmeadow** [comment]
I'm also seeing this problem.

**Comment by siliconmeadow** [comment]
@rogeriopradoj - I've created an image at `siliconmeadow/docker-github-pages` if you want to try the image without creating it yourself.
