### ISSUE TITLE
Could not find i18n-0.8.6 in any of the sources

### ISSUE THREAD

**Issue by wcoder** [Starefossen/docker-github-pages#47]
Command:
```
docker run --name "blog" -v "$PWD":/usr/src/app -p "4000:4000" starefossen/github-pages
```

Logs:
```
Unable to find image 'starefossen/github-pages:latest' locally
latest: Pulling from starefossen/github-pages
ff3a5c916c92: Pull complete
8e2da6035957: Pull complete
42e99ed6de92: Pull complete
70c638bbd0d9: Pull complete
347588c2c13c: Pull complete
3ee934533da5: Pull complete
b0b3e87bd53d: Pull complete
Digest: sha256:22cdc5603886daea887da7890ef930551d04b470f527e875019167db835eec4b
Status: Downloaded newer image for starefossen/github-pages:latest
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find i18n-0.8.6 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
	from /usr/local/bundle/gems/jekyll-3.6.2/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-3.6.2/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:23:in `load'
	from /usr/local/bundle/bin/jekyll:23:in `<main>'
```

**Comment by chadmayfield** [comment]
+1, I'm having the same issue.

**Comment by raphaelmerx** [comment]
Just ran into the same issue, but related to finding `commonmarker-0.17.9` instead:
```
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find commonmarker-0.17.9 in any of the sources (Bundler::GemNotFound)
```

**Comment by jrudolph** [comment]
Removing Gemfile.lock helped for me
